### PR TITLE
added initial files to be worked in

### PR DESCRIPTION
**Pull request by ghost**
I added the initial files for us to do our code within!

### CODE REVIEW

**Review by kevinfukuhara — DISMISSED** [review]
Pretty standard file skeleton. No need for reset.css because we'll be using Bootstrap

**Review by Ebrimasaho1 — APPROVED** [review]
Initial file creations successful.

**Comment by ghost** [comment]
If we dont need the reset file couldnt we just not link it in the html and leav it within the files in case we might need it later for some other reason

**Review by kevinfukuhara — APPROVED** [review]
Approved

**Pull request merged**
